# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: myPassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080